name: huggingface_dart
description: "Utilities to use the Hugging Face hub API"
version: 0.0.2
repository: https://github.com/shivance/huggingface.dart

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  http: ^1.1.2
  dotenv: ^4.2.0

dev_dependencies:
  test: '^1.25.0'
  lints: '^3.0.0'
  build_runner: '^2.4.6'
  build_test: '^2.2.2'
  build_web_compilers: '^4.0.6'